name: Test Program
run-name: test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: build
        run: make

      - name: test
        run: ./build/decoder --test

